name: composite action

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        uses: poonkundran95/repo1/.github/actions/my-composite-action@main
        with:
          node-version: '18'
