name: My OUTPUT workflow
on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: unbuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: unbuntu-latest
    needs: job1
    steps:
      - env:
          OUT1: ${{needs.job1.outputs.output1}}
          OUT2: ${{needs.job1.outputs.output1}}
        run: echo "$OUT1 $OUT2"
        
