name: composite action

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        uses: ../actions/my-composite-action
        with:
          node-version: '18'
